### ISSUE TITLE
pdfminer failed to get all text of the pdf file

### ISSUE THREAD

**Issue by BigPandaCPU** [euske/pdfminer#274]
Dear sir:
    I use pdf2txt  to get the txt of the pdf file,but it only get some parts of the txt. I don't know how to solve this problem.Could you please give me some advise. Thanks a lot.
![QQ截图20191209093742](https://user-images.githubusercontent.com/25834151/70400825-c8245780-1a67-11ea-9703-2a61ba42c710.png)

**Comment by himanshugarg** [comment]
Sorry, which parts are NOT extracted?

**Comment by BigPandaCPU** [comment]
> Sorry, which parts are NOT extracted?

only get the red rectangle parts，the  orry, which parts are NOT extracted?

only get the red rectangle parts，the  above parts（blue rectange parts） failed  to get. The test pdf file i s below.
[test1.pdf](https://github.com/euske/pdfminer/files/3943122/test1.pdf)

**Comment by himanshugarg** [comment]
Seems to work for me:-

 12 AConstituent-CentricNeuralArchitectureforReadingComprehensionPengtaoXie*†andEricP    .Xing†*MachineLearningDepartment,CarnegieMellonUniversity†PetuumInc.pengtaox@cs.c    mu.edu,eric.xing@petuum.comAbstractReadingcomprehension(RC),aimingtounderstandnat    uraltextsandanswerques-tionstherein,isachallengingtask.Inthispaper,westudytheRCpr    oblemontheStanfordQuestionAnsweringDataset(SQuAD).Observingfromthetrainingsetthat    mostcorrectanswersarecenteredaroundconstituentsintheparsetree,wedesignaconstituen    t-centricneuralarchi-tecturewherethegenerationofcandidateanswersandtheirrepresent    ationlearningarebothbasedonconstituentsandguidedbytheparsetree.Underthisarchitec-    ture,thesearchspaceofcandidateanswerscanbegreatlyreducedwithoutsacriﬁcingthecover    ageofcorrectanswersandthesyntactic,hierarchicalandcompositionalstructureamongcons    tituentscanbewellcaptured,whichcontributestobetterrep-resentationlearningofthecan    didatean-swers.OnSQuAD,ourmethodachievesthestateoftheartperformanceandtheab-latio    nstudycorroboratestheeffectivenessofindividualmodules.1IntroductionReadingcompreh    ension(RC)aimstoanswerquestionsbyunderstandingtexts,whichisachal-lengetaskinnatur    allanguageprocessing.Var-iousRCtasksanddatasetshavebeendevel-oped,includingMachin    eComprehensionTest(Richardsonetal.,2013)formultiple-choiceques-tionanswering(QA)(    Sachanetal.,2015;WangandMcAllester,2015),Algebra(Hosseinietal.,2014)andScience(Cl    arkandEtzioni,2016)forpassingstandardizedtests(Clarketal.,2016),CNN/DailyMail(Her    mannetal.,2015)andChil-dren’sBookTest(Hilletal.,2015)forcloze-style The most auth    oritative account at the time came from the medical faculty in Paris in a report     to the king of France that blamed the heavens. This report became the first and m    ost widely circulated of a series of plague tracts that sought to give advice to     sufferers. That the plague was caused by bad air became the most widely accepted     theory. Today, this is known as the Miasma theory.  1. Who was the medical report     written for?                    the king of France 2. What is the newer, more wi    dely accepted theory behind the spread of the plague?                                      bad air 3. What is the bad air theory officially known as?    Miasma theory     Figure1:AnexampleoftheSQuADQAtaskQA(Chenetal.,2016;Shenetal.,2016),Wik-iQA(Yange    tal.,2015),StanfordQuestionAn-sweringDataset(SQuAD)(Rajpurkaretal.,2016)andMicros    oftMachineReadingComprehension(Nguyenetal.,2016)foropendomainQA.Inthispaper,weare    speciﬁcallyinterestedinsolvingtheSQuADQAtask(Figure1showsanexample),inlightofitsf    ollowingfeatures:(1)largescale:107,785questions,23,215paragraphs;(2)non-synthetic    :questionsaregeneratedbycrowdwork-ers;(3)largesearchspaceofcandidateanswers.Westu    dytwomajorproblems:(1)howtogeneratecandidateanswers?Unlikeinmultiple-choiceQAandc    loze-styleQAwhereasmallamountofanswerchoicesaregiven,ananswerinSQuADcouldbeanyspa    ninthetext,resultinginalargesearchspacewithsizeO(n2)(Rajpurkaretal.,2016),whereni    sthenumberofwordsinthesentence.Thiswouldincuralotofnoise,ambigu-^L1406

**Comment by BigPandaCPU** [comment]
Yes,Tannks a lot. It get all  the texts,but it not output in order as we see in pdf file, so I made the mistake.
